language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ssharaths/docker1-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ssharaths/docker1-react npm run test
